spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Rhkrrhkr12!
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
server:
  port: 7777
  servlet:
      context-path: /api
